apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nightglow.orderout.io_browserlesspools.yaml
  - nightglow.orderout.io_browsersessions.yaml
  - nightglow.orderout.io_automationtasks.yaml
  - nightglow.orderout.io_taskrecords.yaml
